### ISSUE TITLE
Event handlers being registered from this library are not extensible

### ISSUE THREAD

**Issue by chrisinajar** [xiel/wheel-gestures#372]
It would appear that the event handlers coming out of this library and into `addEventListener` are not extensible via `Object.preventExtensions` or similar. This is problematic with exception trackers such as Sentry or LogRocket as they rely on leaving behind properties on the functions to keep track of wrapped methods. In fact, LogRocket fully throws exceptions when used with this library since it executes in strict mode (https://github.com/LogRocket/logrocket/issues/17).

The functions being passed into addEventListener, and other native methods external to this library, should not be locked down or frozen in any way.

**Comment by xiel** [comment]
Hey @chrisinajar ,

thanks for reporting this. I will check if I can reproduce this error with LogRocket, if I can help to avoid it.

**Comment by chrisinajar** [comment]
> Hey @chrisinajar ,
> 
> thanks for reporting this. I will check if I can reproduce this error with LogRocket and if I can help to avoid it.

You can reproduce it pretty easily by replacing HTMLElement.addEventListener with a `strict mode` function that adds a property to the second argument. Thanks for looking in to it!

**Comment by xiel** [comment]
Although I think LogRocket should adjust their code and not attempt write on other peoples objects/functions, I removed the freeze on the callbacks for now and published patch versions:

- wheel-gestures@2.2.1
- embla-carousel-wheel-gestures@1.0.4

Cheers,
– Felix
