### ISSUE TITLE
e.stopPropagation option (feature request)

### ISSUE THREAD

**Issue by robinscholz** [xiel/wheel-gestures#706]
Hi xiel, 

Thanks for this great library! We‘ve just implemented it in a [Vue drawer component](https://vue-equipment.maas.engineering/plugins/MagicDrawer/). 

One thing I noticed is that the wheel event will propagate, with no option to prevent this. It’d be great if the options could be expanded to include something similar to the `preventWheelAction` implementation.

If you’d like I can work on a pull request, just thought I’d ask if this would make sense before looking into details.

**Comment by xiel** [comment]
You should be able to stop propagation if needed using:

```js
wheelGestures.on('wheel', (wheelEventState) => {
  wheelEventState.event.stopPropagation()
})
```

In which case is that better than preventDefault?
