### ISSUE TITLE
DevDependencies listed as Dependencies

### ISSUE THREAD

**Issue by Mitch-At-Work** [xiel/wheel-gestures#721]
It seems both '@babel/plugin-proposal-private-property-in-object' and 'jest-environment-jsdom' can be local devDependencies to prevent unnecessary package inclusion for consuming repositories.

We are seeing these deps added via consuming embla-carousel-wheel-gestures (https://www.npmjs.com/package/embla-carousel-wheel-gestures) and believe they could be moved to dev dependencies to reduce unneeded package inclusion.

PR included: https://github.com/xiel/wheel-gestures/pull/720

**Comment by xiel** [comment]
Thanks for opening the issue and fixing! 👌
